package lyc.compiler;

import java_cup.runtime.*;
import lyc.compiler.model.SymbolTable;
import lyc.compiler.model.SymbolEntry;
import lyc.compiler.model.SymbolType;
import java.util.List;
import java.util.ArrayList;

class Parser;


// terminales
terminal ASSIG;
terminal PLUS;
terminal SUB;
terminal MULT;
terminal DIV;
terminal MOD;
terminal DIV_INT;
terminal OPEN_BRACKET;
terminal CLOSE_BRACKET;
terminal OPEN_BRACE;
terminal CLOSE_BRACE;
terminal OPEN_SQUARE_BRACKET;
terminal CLOSE_SQUARE_BRACKET;
terminal COLON;
terminal COMMA;
terminal EQ;
terminal LT;
terminal GT;
terminal LE;
terminal GE;
terminal NE;
terminal INTEGER_CONSTANT;
terminal FLOAT_CONSTANT;
terminal STRING_CONSTANT;
terminal IDENTIFIER;
terminal INIT;
terminal FLOAT_TYPE;
terminal INT_TYPE;
terminal STRING_TYPE;
terminal IF;
terminal ELSE;
terminal WHILE;
terminal WHILE_SPECIAL;
terminal READ;
terminal WRITE;
terminal AND;
terminal OR;
terminal NOT;
terminal IN;
terminal DO;
terminal ENDWHILE;
terminal UMINUS; // terminal ficticio para precedencia unaria

// no terminales
non terminal program;
non terminal init_block;
non terminal decl_list;
non terminal decl;
non terminal List id_list;
non terminal SymbolType type;
non terminal sent_list;
non terminal sent;
non terminal assignment_sent;
non terminal if_sent;
non terminal while_sent;
non terminal special_while_sent;
non terminal read_sent;
non terminal write_sent;
non terminal expr_list;
non terminal expression;
non terminal term;
non terminal factor_u;
non terminal factor;
non terminal condition;
non terminal cond_and;
non terminal cond_not;
non terminal cond_atom;
non terminal simple_condition;
non terminal comp_op;

// precedencia
precedence left PLUS, SUB;
precedence left MULT, DIV;
precedence right UMINUS;

start with program;

program ::= init_block sent_list {: System.out.println("Program completed"); :};
program ::= init_block {: System.out.println("Program with init only"); :};
program ::= sent_list {: System.out.println("Program completed"); :};
program ::= {: System.out.println("Empty program"); :};

init_block ::= INIT OPEN_BRACE decl_list CLOSE_BRACE {: System.out.println("Init block completed"); :};

decl_list ::= decl_list decl {: System.out.println("Multiple declarations"); :};
decl_list ::= decl {: System.out.println("First declaration"); :};

// cuando se declara una variable la agrego a la tabla de simbolos
decl ::= id_list:ids COLON type:t {:
    String typeName = t == SymbolType.FLOAT ? "Float" : (t == SymbolType.INT ? "Int" : "String");
    for (Object id : ids) {
        String variableName = (String) id;
        SymbolTable.getInstance().add(new SymbolEntry(variableName, t));
        System.out.println("Variable added to table: " + variableName + " (-)");
    }
    System.out.println("Type: " + typeName);
    System.out.println("Variable declaration with type: " + typeName);
:};

id_list ::= id_list:lista COMMA IDENTIFIER:id {:
    System.out.println("," + id);
    lista.add((String) id);
    RESULT = lista;
:};
id_list ::= IDENTIFIER:id {:
    System.out.println("Variable: " + id);
    List<String> nueva = new ArrayList<>();
    nueva.add((String) id);
    RESULT = nueva;
:};

type ::= FLOAT_TYPE {: RESULT = SymbolType.FLOAT; :};
type ::= INT_TYPE {: RESULT = SymbolType.INT; :};
type ::= STRING_TYPE {: RESULT = SymbolType.STRING; :};

sent_list ::= sent_list sent;
sent_list ::= sent;

sent ::= assignment_sent;
sent ::= if_sent;
sent ::= while_sent;
sent ::= special_while_sent;
sent ::= read_sent;
sent ::= write_sent;

assignment_sent ::= IDENTIFIER:id ASSIG expression {: System.out.println("Assignment: " + id + " = (expr)"); :};

// if con y sin else
if_sent ::= IF OPEN_BRACKET condition CLOSE_BRACKET OPEN_BRACE sent_list CLOSE_BRACE {: System.out.println("If"); :};
if_sent ::= IF OPEN_BRACKET condition CLOSE_BRACKET OPEN_BRACE sent_list CLOSE_BRACE ELSE OPEN_BRACE sent_list CLOSE_BRACE {: System.out.println("If-else"); :};

//while sentence
while_sent ::= WHILE {: System.out.println("While"); :}
               OPEN_BRACKET condition CLOSE_BRACKET OPEN_BRACE sent_list CLOSE_BRACE;
               
// tema especial: ciclo especial con lista de valores
special_while_sent ::= WHILE_SPECIAL IDENTIFIER IN OPEN_SQUARE_BRACKET expr_list CLOSE_SQUARE_BRACKET DO sent_list ENDWHILE;

expr_list ::= expr_list COMMA expression;
expr_list ::= expression;

read_sent  ::= READ OPEN_BRACKET IDENTIFIER:id CLOSE_BRACKET {: System.out.println("Read: " + id); :};
write_sent ::= WRITE OPEN_BRACKET expression CLOSE_BRACKET {: System.out.println("Write"); :};

// condition
condition ::= condition OR cond_and {: System.out.println("Operator: OR"); :};
condition ::= cond_and;

cond_and ::= cond_and AND cond_not {: System.out.println("Operator: AND"); :};
cond_and ::= cond_not;

cond_not ::= NOT cond_not {: System.out.println("Operator: NOT"); :};
cond_not ::= cond_atom;

cond_atom ::= simple_condition;
cond_atom ::= OPEN_BRACKET condition CLOSE_BRACKET;

simple_condition ::= expression comp_op expression;

comp_op ::= EQ {: System.out.println("Operator: =="); :}; // ==
comp_op ::= LT {: System.out.println("Operator: <"); :};  // <
comp_op ::= GT {: System.out.println("Operator: >"); :};  // >
comp_op ::= LE {: System.out.println("Operator: <="); :}; // <=
comp_op ::= GE {: System.out.println("Operator: >="); :}; // >=
comp_op ::= NE {: System.out.println("Operator: !="); :}; // !=

expression ::= expression PLUS term {: System.out.println("Operator: +"); :};
expression ::= expression SUB  term {: System.out.println("Operator: -"); :};
expression ::= term;

// tema especial: MOD y DIV
term ::= term MULT    factor_u {: System.out.println("Operator: *"); :};
term ::= term DIV     factor_u {: System.out.println("Operator: /"); :};
term ::= term MOD     factor_u {: System.out.println("Operator: MOD"); :};
term ::= term DIV_INT factor_u {: System.out.println("Operator: DIV"); :};
term ::= factor_u;

factor_u ::= SUB factor {: System.out.println("factor_u -> - factor"); :} %prec UMINUS;
factor_u ::= PLUS factor {: System.out.println("factor_u -> + factor"); :} %prec UMINUS;
factor_u ::= factor {: System.out.println("factor_u -> factor"); :};

factor ::= IDENTIFIER:id {: System.out.println("Id: " + id); :};
factor ::= INTEGER_CONSTANT:c {:
    String val = (String) c;
    System.out.println("Integer: " + val);
    if (!SymbolTable.getInstance().contains(val)) {
        SymbolEntry e = new SymbolEntry(val, SymbolType.INT);
        e.setValue(val);
        SymbolTable.getInstance().add(e);
    }
:};
factor ::= FLOAT_CONSTANT:c {:
    String val = (String) c;
    System.out.println("Float: " + val);
    if (!SymbolTable.getInstance().contains(val)) {
        SymbolEntry e = new SymbolEntry(val, SymbolType.FLOAT);
        e.setValue(val);
        SymbolTable.getInstance().add(e);
    }
:};
factor ::= STRING_CONSTANT:c {:
    String val = (String) c;
    System.out.println("String: " + val);
    if (!SymbolTable.getInstance().contains(val)) {
        SymbolEntry e = new SymbolEntry(val, SymbolType.STRING);
        e.setValue(val);
        SymbolTable.getInstance().add(e);
    }
:};
factor ::= OPEN_BRACKET expression CLOSE_BRACKET;
